### ISSUE TITLE
Timeout would be nice too!

### ISSUE THREAD

**Issue by Jaciones** [emcien/iso_latte#1]
This is very cool. I timeout option would be very useful too. That kinda covers the last condition of "my subprocess has been zombified and doesn't like it's ever going to return".

**Comment by nevinera** [comment]
I like that! It'll take a few minutes though, `Thread`s always do.

**Comment by nevinera** [comment]
I would prefer to send a TERM, wait a second, then send a KILL, and may implement that later. It's a bit of a tangle of timeouts, though, and I don't have a good way to write tests for timeouts at all yet.

I released 1.1 with the 'timeout' option though - for now it just sends a KILL to the child after the timeout, and tries to be safe about the obvious race condition (if it decides to kill the child at the same time the child exits, we should get an `Errno::ESRCH`).

**Comment by nevinera** [comment]
(issue will be continued in #3)
